# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "kibali"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daudi Amani"]
  s.date = "2012-11-23"
  s.description = "simple Rails role authentication"
  s.email = "dsaronin@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/kibali.rb",
    "lib/kibali/access_control.rb",
    "lib/kibali/base.rb",
    "lib/kibali/control.rb",
    "lib/kibali/railtie.rb",
    "lib/kibali/subject_extensions.rb",
    "markdown.rb",
    "test/app/controllers/application_controller.rb",
    "test/app/controllers/empty_controller.rb",
    "test/config.ru",
    "test/config/routes.rb",
    "test/ctlr_helper.rb",
    "test/factories/units_factory.rb",
    "test/helper.rb",
    "test/script/rails",
    "test/support/models.rb",
    "test/support/schema.rb",
    "test/test_access.rb",
    "test/test_kibali.rb"
  ]
  s.homepage = "http://github.com/dsaronin@gmail.com/kibali"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "rails role authentication"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.2.8"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.2.8"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.2.8"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
  end
end

